name: 'Gemini PR Reviewer'
description: 'Review Pull Requests using the Google Gemini API'
author: 'Vivek Raj'

inputs:
  github-token:
    description: 'GitHub token for accessing the repository and posting comments'
    required: true
  gemini-api-key:
    description: 'API key for Google Gemini'
    required: true
runs:
  using: 'node20'
  main: 'dist/index.js'

branding:
  icon: 'cpu'        
  color: 'blue'
